// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIz aSyA-hPCGeZTRFS8HLP5asaJlee-oOEmpJgE',
    appId: '1:76264690945:web:a2d511c1e3e5ae0d277700',
    messagingSenderId: '76264690945',
    projectId: 'ntmdev-e248a',
    authDomain: 'ntmdev-e248a.firebaseapp.com',
    databaseURL: 'https://ntmdev-e248a.firebaseio.com',
    storageBucket: 'ntmdev-e248a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtI41T9v3iqHGtqeuoraSROkw4sbwLgB4',
    appId: '1:76264690945:android:74c2c309e2117f2a277700',
    messagingSenderId: '76264690945',
    projectId: 'ntmdev-e248a',
    databaseURL: 'https://ntmdev-e248a.firebaseio.com',
    storageBucket: 'ntmdev-e248a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeWow7-np_NzGrDBRGCFIKbmS0SB_Zj6I',
    appId: '1:76264690945:ios:7584e17757e45f73277700',
    messagingSenderId: '76264690945',
    projectId: 'ntmdev-e248a',
    databaseURL: 'https://ntmdev-e248a.firebaseio.com',
    storageBucket: 'ntmdev-e248a.appspot.com',
    iosClientId: '76264690945-ems96r19ld63if1nsml6tg1g4ulij08b.apps.googleusercontent.com',
    iosBundleId: 'com.example.appleFitnessFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeWow7-np_NzGrDBRGCFIKbmS0SB_Zj6I',
    appId: '1:76264690945:ios:7584e17757e45f73277700',
    messagingSenderId: '76264690945',
    projectId: 'ntmdev-e248a',
    databaseURL: 'https://ntmdev-e248a.firebaseio.com',
    storageBucket: 'ntmdev-e248a.appspot.com',
    iosClientId: '76264690945-ems96r19ld63if1nsml6tg1g4ulij08b.apps.googleusercontent.com',
    iosBundleId: 'com.example.appleFitnessFlutter',
  );
}
